// ********** AUTH **********
export const TEST_API_REQUEST = 'TEST_API_REQUEST';
export const TEST_API_SUCCESS = 'TEST_API_SUCCESS';
export const TEST_API_ERROR = 'TEST_API_ERROR';

export const CHANGE_PIN_REQUEST = 'CHANGE_PIN_REQUEST';
export const CHANGE_PIN_SUCCESS = 'CHANGE_PIN_SUCCESS';
export const CHANGE_PIN_ERROR = 'CHANGE_PIN_ERROR';

export const SET_DISP_ENV_REQUEST = 'SET_DISP_ENV_REQUEST';
export const SET_DISP_ENV_SUCCESS = 'SET_DISP_ENV_SUCCESS';
export const SET_DISP_ENV_ERROR = 'SET_DISP_ENV_ERROR';

export const BAR_CODE_RESET = 'BAR_CODE_RESET';
export const BAR_CODE_ACTION = 'BAR_CODE_ACTION';
export const BAR_CODE_SUCCESS = 'BAR_CODE_SUCCESS';
export const BAR_CODE_ERROR = 'BAR_CODE_ERROR';

export const INITIAL = 'INITIAL';
export const INITIALIZE_SESSION = 'INITIALIZE_SESSION';

export const LOGIN_USER_WITHOUT_PIN = 'LOGIN_USER_WITHOUT_PIN';

export const AZURE_LOGIN = 'AZURE_LOGIN';

export const LOGIN_USER = 'LOGIN_USER';
export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS';
export const LOGIN_USER_ERROR = 'LOGIN_USER_ERROR';

export const LOGOUT_REQUEST = 'LOGOUT_REQUEST';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';

export const SESSION_EXPIRE_REQUEST = 'SESSION_EXPIRE_REQUEST';
export const SESSION_EXPIRE_SUCCESS = 'SESSION_EXPIRE_SUCCESS';

export const GET_USER_STATE_REQUEST = 'GET_USER_STATE_REQUEST';
export const GET_USER_STATE_SUCCESS = 'GET_USER_STATE_SUCCESS';

export const GET_SCREEN_REQUEST = 'GET_SCREEN_REQUEST';
export const GET_SCREEN_REQUEST_DATA = 'GET_SCREEN_REQUEST_DATA';
export const GET_BUTTON_SCREEN_SUCCESS = 'GET_BUTTON_SCREEN_SUCCESS';
export const GET_SCREEN_SUCCESS = 'GET_SCREEN_SUCCESS';
export const GET_SCREEN_ERROR = 'GET_SCREEN_ERROR';
export const GO_BACK = 'GO_BACK';
export const CLEAR_SCREEN_DETAIL = 'CLEAR_SCREEN_DETAIL';

export const GET_LOCAL_CURRENT_SCREEN = 'GET_LOCAL_CURRENT_SCREEN';

export const GET_LOCATION_LIST_REQUEST = 'GET_LOCATION_LIST_REQUEST';
export const GET_LOCATION_LIST_SUCCESS = 'GET_LOCATION_LIST_SUCCESS';

export const GET_PARTNER_LIST_REQUEST = 'GET_PARTNER_LIST_REQUEST';
export const GET_PARTNER_LIST_SUCCESS = 'GET_PARTNER_LIST_SUCCESS';

// ********** GOODS IN **********
export const GET_DOCK_TO_STOCK_REQUEST = 'GET_DOCK_TO_STOCK_REQUEST';
export const GET_DOCK_TO_STOCK_SUCCESS = 'GET_DOCK_TO_STOCK_SUCCESS';

export const SET_DOC_DATA_LOG_REQUEST = 'SET_DOC_DATA_LOG_REQUEST';
export const SET_DOC_DATA_LOG_SUCCESS = 'SET_DOC_DATA_LOG_SUCCESS';
export const RESET_DOCK_TO_STOCK = 'RESET_DOCK_TO_STOCK';

// ********** INVENTORY CONTROL **********
export const GET_START_STOCK_MOVE_REQUEST = 'GET_START_STOCK_MOVE_REQUEST';
export const GET_START_STOCK_MOVE_SUCCESS = 'GET_START_STOCK_MOVE_SUCCESS';
export const GET_CANCLE_STOCK_MOVE_REQUEST = 'GET_CANCLE_STOCK_MOVE_REQUEST';
export const GET_CANCLE_STOCK_MOVE_SUCCESS = 'GET_CANCLE_STOCK_MOVE_SUCCESS';
export const GET_MASTER_LOC_REQUEST = 'GET_MASTER_LOC_REQUEST';
export const GET_MASTER_LOC_SUCCESS = 'GET_MASTER_LOC_SUCCESS';
export const GET_SET_MASTER_LOC_REQUEST = 'GET_SET_MASTER_LOC_REQUEST';
export const GET_SET_MASTER_LOC_SUCCESS = 'GET_SET_MASTER_LOC_SUCCESS';
export const GET_STOCK_MOVE_QTY_REQUEST = 'GET_STOCK_MOVE_QTY_REQUEST';
export const GET_STOCK_MOVE_QTY_SUCCESS = 'GET_STOCK_MOVE_QTY_SUCCESS';
export const GET_STOCK_MOVE_DETAIL_SUCCESS = 'GET_STOCK_MOVE_DETAIL_SUCCESS';
export const CONFORM_MOVE_TO_MASTER_LOC = 'CONFORM_MOVE_TO_MASTER_LOC';
export const CLEAR_STOCK_MOVE = 'CLEAR_STOCK_MOVE';

// ********** ESCALATION **********
export const GET_ESCALATION_PRINT_REQUEST = 'GET_ESCALATION_PRINT_REQUEST';
export const GET_ESCALATION_PRINT_SUCCESS = 'GET_ESCALATION_PRINT_SUCCESS';

// ********** ERROR & MESSAGE & LOADING **********
export const SET_LOADING = 'SET_LOADING';
export const SET_LOADING_GLOBAL = 'SET_LOADING_GLOBAL';
export const CLEAR_MESSAGE = 'CLEAR_MESSAGE';
export const CLEAR_ERROR = 'CLEAR_ERROR';
export const CLEAR_STATES = 'CLEAR_STATES';
